server:
  port: 32700
  servlet:
    context-path: /jwtTokenProvider

jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub

spring:
  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jwt_adm_user
    password: aR7Ea16ZiJjD
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/jwtDatabase
