services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=jwt_adm_user
      - MYSQL_PASSWORD=aR7Ea16ZiJjD
      - MYSQL_DATABASE=jwtDatabase
      - MYSQL_ROOT_PASSWORD=WeRQv7mDQnnK