name: JWT Server build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: gradle build

#      - name: Upload build artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: Package
#          path: build/libs
